"""A block manager that manages token blocks by layer."""

from typing import Dict, List, Optional
from typing import Sequence as GenericSequence
from typing import Tuple

from vllm.core.block.block_table import BlockTable
from vllm.core.block.cpu_gpu_block_allocator import CpuGpuBlockAllocator
from vllm.core.block.interfaces import Block
from vllm.core.block.prefix_caching_block import (ComputedBlocksTracker,
                                                  LastAccessBlocksTracker)
from vllm.core.block.utils import check_no_caching_or_swa_for_blockmgr_encdec
from vllm.core.interfaces import AllocStatus, BlockSpaceManager
from vllm.sequence import Sequence, SequenceGroup, SequenceStatus
from vllm.utils import Device

SeqId = int
EncoderSeqId = str


class LayerBlockSpaceManager(BlockSpaceManager):
    """LayerBlockSpaceManager which manages the allocation of KV cache by layer.

    It is responsible for allocation, swapping, and allocating memory for
    tokens generated by autoregression, and currently does not support
    other advanced features such as prefix caching, and sliding window
    memory allocation but supported forking/copy-on-write.



    Args:
        BlockSpaceManager (_type_): _description_
    """

    def __init__(
        self,
        block_size: int,
        num_gpu_blocks: int,
        num_cpu_blocks: int,
        watermark: float = 0.01,
        sliding_window: Optional[int] = None,
        enable_caching: bool = False,
        **kwargs,
    ) -> None:
        self.block_size = block_size
        self.num_gpu_blocks = num_gpu_blocks
        self.num_cpu_blocks = num_cpu_blocks
        if "num_attn_layers" in kwargs:
            self.num_attn_layers = kwargs["num_attn_layers"]
        else:
            raise ValueError("num_attn_layers is required.")

        # LayerBlockSpaceManager does not support prefix caching or sliding
        # window now.
        self.sliding_window = sliding_window
        self.max_block_sliding_window = None
        assert self.sliding_window is None
        self.enable_caching = enable_caching
        assert not self.enable_caching

        self.watermark = watermark
        assert 0.0 <= self.watermark <= 1.0

        self.watermark_blocks = int(watermark * num_gpu_blocks)

        # TODO CpuGpuBlockAllocator should be a new class supporting layer block
        self.block_allocator = CpuGpuBlockAllocator.create(
            allocator_type="prefix_caching" if enable_caching else "naive",
            num_gpu_blocks=num_gpu_blocks,
            num_cpu_blocks=num_cpu_blocks,
            block_size=block_size,
        )

        self.layer_block_tables: List[Dict[SeqId, BlockTable]] = [
            {} for _ in range(self.num_attn_layers)
        ]
        # self.layer_cross_block_tables: List[Dict[EncoderSeqId, BlockTable]] =
        # [
        #     {} for _ in range(num_attn_layers)
        # ]

        # LayerBlockSpaceManager does not support encoder model
        # self.cross_block_tables: Dict[EncoderSeqId, BlockTable] = {}

        # LayerBlockSpaceManager does not support prefix caching
        self._computed_blocks_tracker = ComputedBlocksTracker(
            self.block_allocator)
        self._last_access_blocks_tracker = LastAccessBlocksTracker(
            self.block_allocator)

    def block_tables(self, layer: int) -> Dict[SeqId, BlockTable]:
        return self.layer_block_tables[layer]

    def can_allocate(self,
                     seq_group: SequenceGroup,
                     num_lookahead_slots: int = 0) -> AllocStatus:
        # 该函数在调度prefill阶段时调用，判断是否可以分配时考虑所有层的block数

        # FIXME(woosuk): Here we assume that all sequences in the group share
        # the same prompt. This may not be true for preempted sequences.

        check_no_caching_or_swa_for_blockmgr_encdec(self, seq_group)

        seq = seq_group.get_seqs(status=SequenceStatus.WAITING)[0]
        # Compute block numbers required for the sequence all layers.
        num_required_blocks = (self.num_attn_layers *
                               BlockTable.get_num_required_blocks(
                                   seq.get_token_ids(),
                                   self.block_size,
                               ))

        if seq_group.is_encoder_decoder():
            raise NotImplementedError(
                "Encoder-decoder model is not supported.")
        if self.max_block_sliding_window is not None:
            raise NotImplementedError("Sliding window is not supported.")

        num_free_gpu_blocks = self.block_allocator.get_num_free_blocks(
            device=Device.GPU)

        # Use watermark to avoid frequent cache eviction.
        if num_free_gpu_blocks - num_required_blocks < self.watermark_blocks:
            return AllocStatus.NEVER
        if num_free_gpu_blocks - num_required_blocks >= self.watermark_blocks:
            return AllocStatus.OK
        else:
            return AllocStatus.LATER

    def _allocate_sequence(self, seq: Sequence) -> List[BlockTable]:
        """
        Allocate blocks for all attention layers of the sequence for prefill.
        """
        block_table_list: List[BlockTable] = []
        for _ in range(self.num_attn_layers):
            block_table = BlockTable(
                block_size=self.block_size,
                block_allocator=self.block_allocator,
            )
            if seq.get_token_ids():
                # TODO: check if this is correct, can a token_ids appear in
                # multiple block_tables of different layers?
                block_table.allocate(seq.get_token_ids())
            block_table_list.append(block_table)
        return block_table_list

    def allocate(self, seq_group: SequenceGroup) -> None:
        # NOTE: only called by prefill phase to allocate blocks
        #  for all layers of the seq_group
        waiting_seqs = seq_group.get_seqs(status=SequenceStatus.WAITING)
        # NOTE: Why?
        assert not (set(seq.seq_id for seq in waiting_seqs)
                    & self.block_tables(0).keys()
                    ), "block table already exists(layer0)"

        # NOTE: Here we assume that all sequences in the group have the same
        # prompt.
        seq = waiting_seqs[0]
        block_table_list: List[BlockTable] = self._allocate_sequence(seq)
        for layer, block_table in enumerate(block_table_list):
            self.layer_block_tables[layer][seq.seq_id] = block_table

        # Track seq,not supported now
        # self._computed_blocks_tracker.add_seq(seq.seq_id)
        # self._last_access_blocks_tracker.add_seq(seq.seq_id)

        # Assign the block tables for all layers of each sequence
        for seq in waiting_seqs[1:]:
            for layer, block_table in enumerate(block_table_list):
                self.layer_block_tables[layer][seq.seq_id] = block_table.fork()

        # TODO add cross block tables for encoder-decoder model
        # check_no_caching_or_swa_for_blockmgr_encdec(self, seq_group)

    def get_blocks_count_for_slots(self, seq_group: SequenceGroup,
                                   num_lookahead_slots: int) -> int:
        """Get the number of blocks required to allocate slots for an attention
        layer in the specified seqgroup.
        """
        num_touched_blocks = 0
        for seq in seq_group.get_seqs(status=SequenceStatus.RUNNING):
            block_table = self.block_tables(0)[seq.seq_id]
            num_touched_blocks += (
                block_table.get_num_blocks_touched_by_append_slots(
                    token_ids=block_table.get_unseen_token_ids(
                        seq.get_token_ids()),
                    num_lookahead_slots=num_lookahead_slots,
                ))
        return num_touched_blocks

    def can_append_slots(self, seq_group: SequenceGroup,
                         num_lookahead_slots: int) -> bool:
        """Determine if slots can be allocated for all layers of a seq_group.
        """
        # 不可以在step_layer中调用，因为step_layer中只考虑一个层
        num_touched_blocks = self.get_blocks_count_for_slots(
            seq_group, num_lookahead_slots)
        num_touched_blocks *= self.num_attn_layers
        num_free_gpu_blocks = self.block_allocator.get_num_free_blocks(
            Device.GPU)
        return num_touched_blocks <= num_free_gpu_blocks

    def can_append_slots_batch(self, seq_groups: List[SequenceGroup],
                               num_lookahead_slots: int,
                               num_laysers: int) -> bool:
        # 检查是否可以为running队列中的所有seq_group的所有层分配slots
        # TODO 添加参数，来判断是否所有层还是单个层还是部分层
        # TODO 该函数是否需要转移到scheduler中？
        assert num_laysers <= self.num_attn_layers and num_laysers > 0, \
            "num_layers should be in [1,num_attn_layers]"
        num_touched_blocks = 0
        for seq_group in seq_groups:
            num_touched_blocks += self.get_blocks_count_for_slots(
                seq_group, num_lookahead_slots)
        num_touched_blocks *= num_laysers
        num_free_gpu_blocks = self.block_allocator.get_num_free_blocks(
            Device.GPU)
        return num_touched_blocks <= num_free_gpu_blocks

    def append_slots(
        self,
        seq: Sequence,
        num_lookahead_slots: int,
    ) -> List[Tuple[int, int]]:
        # 为一个seq的所有层分配slots

        assert num_lookahead_slots == 0, "not supported lookahead slots"

        block_table_list = [
            self.block_tables(layer)[seq.seq_id]
            for layer in range(self.num_attn_layers)
        ]
        for block_table in block_table_list:
            block_table.append_token_ids(
                token_ids=block_table.get_unseen_token_ids(
                    seq.get_token_ids()),
                num_lookahead_slots=num_lookahead_slots,
                num_computed_slots=seq.data.get_num_computed_tokens(),
            )

        # return new_cows for all layers
        new_cows = self.block_allocator.clear_copy_on_writes()
        return new_cows

    def free(self, seq: Sequence) -> None:
        seq_id = seq.seq_id

        if seq_id in self.block_tables(0):
            # Already freed or haven't been scheduled yet.
            # Once a sequence is scheduled, it will appear in the block_table of
            # each attention layer, so it is sufficient to check the block_table
            # of layer zero.
            return

        # TODO Update seq block ids with the lateset access time
        # self._last_access_blocks_tracker.update_seq_blocks_last_access(
        # seq_id, self.block_tables[seq.seq_id].physical_block_ids)

        # TODO Untrack seq
        # self._last_access_blocks_tracker.remove_seq(seq_id)
        # self._computed_blocks_tracker.remove_seq(seq_id)

        # Free table/blocks
        for layer in range(self.num_attn_layers):
            self.block_tables(layer)[seq_id].free()
            del self.block_tables(layer)[seq_id]

    def free_cross(self, seq_group: SequenceGroup) -> None:
        # TODO
        pass
        return

    def get_block_table(self, seq: Sequence):
        return None

    def get_block_table_layer(self, seq: Sequence, layer: int) -> List[int]:
        block_ids = self.block_tables(layer)[seq.seq_id].physical_block_ids
        return block_ids

    def get_cross_block_table(self, seq_group: SequenceGroup) -> List[int]:
        # TODO
        return []

    def access_all_blocks_in_seq(self, seq: Sequence, now: float):
        """Same as access_all_blocks_in_seq in SelfAttnBlockSpaceManager."""
        # TODO
        pass

    def mark_blocks_as_computed(self, seq_group: SequenceGroup,
                                token_chunk_size: int):
        # If prefix caching is enabled, mark immutable blocks as computed
        # right after they have been scheduled (for prefill). This assumes
        # the scheduler is synchronous so blocks are actually computed when
        # scheduling the next batch.
        pass

    def get_common_computed_block_ids(
            self, seqs: List[Sequence]) -> GenericSequence[int]:
        # TODO
        return []

    def fork(self, parent_seq: Sequence, child_seq: Sequence) -> None:
        if parent_seq.seq_id not in self.block_tables(0):
            return
        src_block_tables = [
            self.block_tables(layer)[parent_seq.seq_id]
            for layer in range(self.num_attn_layers)
        ]
        for layer, src_block_table in enumerate(src_block_tables):
            self.block_tables(layer)[child_seq.seq_id] = src_block_table.fork()

        # Track child seq
        # TODO
        # self._computed_blocks_tracker.add_seq(child_seq.seq_id)
        # self._last_access_blocks_tracker.add_seq(child_seq.seq_id)

    def can_swap_in(self, seq_group: SequenceGroup,
                    num_lookahead_slots: int) -> AllocStatus:
        """Returns the AllocStatus for the given sequence_group 
        (all attn layers) with num_lookahead_slots.

        Args:
            sequence_group (SequenceGroup): The sequence group to swap in.
            num_lookahead_slots (int): Number of lookahead slots used in 
                speculative decoding, default to 0.

        Returns:
            AllocStatus: The AllocStatus for the given sequence group.
        """
        return self._can_swap(seq_group, Device.GPU, SequenceStatus.SWAPPED,
                              num_lookahead_slots)

    def swap_in(self, seq_group: SequenceGroup) -> List[Tuple[int, int]]:
        """Returns the block id mapping (from CPU to GPU) generated by
        swapping in the given seq_group with num_lookahead_slots for all
        attention layers.

        Args:
            seq_group (SequenceGroup): The sequence group to swap in.

        Returns:
            List[Tuple[int, int]]: The mapping of swapping block from CPU 
                to GPU.
        """
        physical_block_id_mapping = []
        for seq in seq_group.get_seqs(status=SequenceStatus.SWAPPED):
            for layer in range(self.num_attn_layers):
                blocks = self.block_tables(layer)[seq.seq_id].blocks
                if len(blocks) == 0:
                    # NOTE: Assume the number of blocks per layer is the same
                    break

                seq_swap_mapping = self.block_allocator.swap(
                    blocks=blocks,
                    src_device=Device.CPU,
                    dst_device=Device.GPU)

                # Refresh the block ids of the table (post-swap)
                # NOTE: After block_allocator.swap, the blocks have been
                # reassigned IDs on the new device.
                self.block_tables(layer)[seq.seq_id].update(blocks)

                seq_physical_block_id_mapping = {
                    self.block_allocator.get_physical_block_id(
                        Device.CPU, cpu_block_id):
                    self.block_allocator.get_physical_block_id(
                        Device.GPU, gpu_block_id)
                    for cpu_block_id, gpu_block_id in seq_swap_mapping.items()
                }
                physical_block_id_mapping.extend(
                    list(seq_physical_block_id_mapping.items()))

        return physical_block_id_mapping

    def can_swap_out(self, seq_group: SequenceGroup) -> bool:
        """Returns whether we can swap out all attn layers of given
        sequence_group with num_lookahead_slots 

        Args:
            seq_group (SequenceGroup): The sequence group to swap out.
            num_lookahead_slots (int): Number of lookahead slots used in 
                speculative decoding, default to 0.

        Returns:
            bool: Whether it's possible to swap out current sequence group.
        """
        alloc_status = self._can_swap(seq_group, Device.CPU,
                                      SequenceStatus.RUNNING)
        return alloc_status == AllocStatus.OK

    def swap_out(self, seq_group: SequenceGroup) -> List[Tuple[int, int]]:
        """Returns the block id mapping (from GPU to CPU) generated by
        swapping out the given sequence_group(all attn layers) with
        num_lookahead_slots.

        Args:
            sequence_group (SequenceGroup): The sequence group to swap out.

        Returns:
            List[Tuple[int, int]]: The mapping of swapping block from 
                GPU to CPU.
        """
        physical_block_id_mapping = []
        for seq in seq_group.get_seqs(status=SequenceStatus.RUNNING):
            for layer in range(self.num_attn_layers):
                blocks = self.block_tables(layer)[seq.seq_id].blocks
                if len(blocks) == 0:
                    # NOTE: Assume the number of blocks per layer is the same
                    break

                seq_swap_mapping = self.block_allocator.swap(
                    blocks=blocks,
                    src_device=Device.GPU,
                    dst_device=Device.CPU)

                # Refresh the block ids of the table (post-swap)
                # NOTE: After block_allocator.swap, the blocks have been
                # reassigned IDs on the new device.
                self.block_tables(layer)[seq.seq_id].update(blocks)

                seq_physical_block_id_mapping = {
                    self.block_allocator.get_physical_block_id(
                        Device.GPU, gpu_block_id):
                    self.block_allocator.get_physical_block_id(
                        Device.CPU, cpu_block_id)
                    for gpu_block_id, cpu_block_id in seq_swap_mapping.items()
                }
                physical_block_id_mapping.extend(
                    list(seq_physical_block_id_mapping.items()))
        return physical_block_id_mapping

    def get_num_free_gpu_blocks(self) -> int:
        return self.block_allocator.get_num_free_blocks(Device.GPU)

    def get_num_free_cpu_blocks(self) -> int:
        return self.block_allocator.get_num_free_blocks(Device.CPU)

    def get_prefix_cache_hit_rate(self, device: Device) -> float:
        return self.block_allocator.get_prefix_cache_hit_rate(device)

    def _can_swap(self,
                  seq_group: SequenceGroup,
                  device: Device,
                  status: SequenceStatus,
                  num_lookahead_slots: int = 0) -> AllocStatus:
        """Returns the AllocStatus for swapping in/out the given sequence_group 
        on to the 'device'.

        Args:
            sequence_group (SequenceGroup): The sequence group to swap in/out.
            device (Device): device to swap the 'seq_group' on.
            status (SequenceStatus): The status of sequence which is needed
                for action. RUNNING for swap out and SWAPPED for swap in
            num_lookahead_slots (int): Number of lookahead slots used in 
                speculative decoding, default to 0.

        Returns:
            AllocStatus: The AllocStatus for swapping in/out the given 
                sequence_group on to the 'device'.
        """
        # First determine the number of blocks that will be touched by this
        # swap. Then verify if there are available blocks in the device
        # to perform the swap.
        num_blocks_touched = 0
        blocks: List[Block] = []
        for seq in seq_group.get_seqs(status=status):
            for layer in range(self.num_attn_layers):
                block_table = self.block_tables(layer)[seq.seq_id]
                if block_table.blocks is not None:
                    # Compute the number blocks to touch for the tokens to be
                    # appended. This does NOT include the full blocks that need
                    # to be touched for the swap.
                    num_blocks_touched +=\
                        block_table.get_num_blocks_touched_by_append_slots(
                            block_table.get_unseen_token_ids(seq.get_token_ids()),
                            num_lookahead_slots=num_lookahead_slots)
                    blocks.extend(block_table.blocks)
        # Compute the number of full blocks to touch and add it to the
        # existing count of blocks to touch.
        num_blocks_touched += self.block_allocator.get_num_full_blocks_touched(
            blocks, device=device)

        watermark_blocks = 0
        if device == Device.GPU:
            watermark_blocks = self.watermark_blocks

        if self.block_allocator.get_num_total_blocks(
                device) < num_blocks_touched:
            return AllocStatus.NEVER
        elif self.block_allocator.get_num_free_blocks(
                device) - num_blocks_touched >= watermark_blocks:
            return AllocStatus.OK
        else:
            return AllocStatus.NEVER
