"""A block manager that manages token blocks by layer."""

from typing import Dict, List, Optional
from typing import Sequence as GenericSequence
from typing import Tuple

from vllm.core.block.block_table import BlockTable
from vllm.core.block.cpu_gpu_block_allocator import CpuGpuBlockAllocator
from vllm.core.block.interfaces import Block
from vllm.core.block.prefix_caching_block import (
    ComputedBlocksTracker,
    LastAccessBlocksTracker,
)
from vllm.core.block.utils import check_no_caching_or_swa_for_blockmgr_encdec
from vllm.core.interfaces import AllocStatus, BlockSpaceManager
from vllm.sequence import Sequence, SequenceGroup, SequenceStatus
from vllm.utils import Device

SeqId = int
EncoderSeqId = str


class LayerBlockSpaceManager(BlockSpaceManager):
    """LayerBlockSpaceManager which manages the allocation of KV cache by layer.

    It is responsible for allocation, swapping, and allocating memory for
    tokens generated by autoregression, and currently does not support
    other advanced features such as prefix caching, and sliding window
    memory allocation but supported forking/copy-on-write.



    Args:
        BlockSpaceManager (_type_): _description_
    """

    def __init__(
        self,
        block_size: int,
        num_gpu_blocks: int,
        num_cpu_blocks: int,
        num_attn_layers: int,
        watermark: float = 0.01,
        sliding_window: Optional[int] = None,
        enable_caching: bool = False,
    ) -> None:
        self.block_size = block_size
        self.num_gpu_blocks = num_gpu_blocks
        self.num_cpu_blocks = num_cpu_blocks
        self.num_attn_layers = num_attn_layers

        # LayerBlockSpaceManager does not support prefix caching or sliding
        # window now.
        self.sliding_window = sliding_window
        self.max_block_sliding_window = None
        assert self.sliding_window is None
        self.enable_caching = enable_caching
        assert not self.enable_caching

        self.watermark = watermark
        assert 0.0 <= self.watermark <= 1.0

        self.watermark_blocks = int(watermark * num_gpu_blocks)

        # TODO CpuGpuBlockAllocator should be a new class supporting layer block
        self.block_allocator = CpuGpuBlockAllocator.create(
            allocator_type="prefix_caching" if enable_caching else "naive",
            num_gpu_blocks=num_gpu_blocks,
            num_cpu_blocks=num_cpu_blocks,
            block_size=block_size,
        )

        self.layer_block_tables: List[Dict[SeqId, BlockTable]] = [
            {} for _ in range(num_attn_layers)
        ]
        # self.layer_cross_block_tables: List[Dict[EncoderSeqId, BlockTable]] =
        # [
        #     {} for _ in range(num_attn_layers)
        # ]

        # LayerBlockSpaceManager does not support encoder model
        # self.cross_block_tables: Dict[EncoderSeqId, BlockTable] = {}

        # LayerBlockSpaceManager does not support prefix caching
        # self._computed_blocks_tracker = ComputedBlocksTracker(
        #     self.block_allocator
        # )
        # self._last_access_blocks_tracker = LastAccessBlocksTracker(
        #     self.block_allocator
        # )

    def block_tables(self, layer: int) -> Dict[SeqId, BlockTable]:
        return self.layer_block_tables[layer]

    def can_allocate(self,
                     seq_group: SequenceGroup,
                     num_lookahead_slots: int = 0) -> AllocStatus:
        # 该函数在调度prefill阶段时调用，判断是否可以分配时考虑所有层的block数

        # FIXME(woosuk): Here we assume that all sequences in the group share
        # the same prompt. This may not be true for preempted sequences.

        check_no_caching_or_swa_for_blockmgr_encdec(self, seq_group)

        seq = seq_group.get_seqs(status=SequenceStatus.WAITING)[0]
        # Compute block numbers required for the sequence all layers.
        num_required_blocks = (self.num_attn_layers *
                               BlockTable.get_num_required_blocks(
                                   seq.get_token_ids(),
                                   self.block_size,
                               ))

        if seq_group.is_encoder_decoder():
            raise NotImplementedError(
                "Encoder-decoder model is not supported.")
        if self.max_block_sliding_window is not None:
            raise NotImplementedError("Sliding window is not supported.")

        num_free_gpu_blocks = self.block_allocator.get_num_free_blocks(
            device=Device.GPU)

        # Use watermark to avoid frequent cache eviction.
        if num_free_gpu_blocks - num_required_blocks < self.watermark_blocks:
            return AllocStatus.NEVER
        if num_free_gpu_blocks - num_required_blocks >= self.watermark_blocks:
            return AllocStatus.OK
        else:
            return AllocStatus.LATER

    def _allocate_sequence_layers(self, seq: Sequence) -> List[BlockTable]:
        # allocate blocks for all layers of the seq
        block_table_list: List[BlockTable] = [] * self.num_attn_layers
        for layer in range(self.num_attn_layers):
            block_table = BlockTable(
                block_size=self.block_size,
                block_allocator=self.block_allocator,
            )
            if seq.get_token_ids():
                # TODO: check if this is correct, can a token_ids appear in
                # multiple block_tables of different layers?
                block_table.allocate(seq.get_token_ids())
            block_table_list[layer] = block_table
        return block_table_list

    def allocate(self, seq_group: SequenceGroup) -> None:
        # NOTE: only called by prefill phase to allocate blocks
        #  for all layers of the seq_group
        waiting_seqs = seq_group.get_seqs(status=SequenceStatus.WAITING)
        # NOTE: Why?
        assert not (set(seq.seq_id for seq in waiting_seqs)
                    & self.block_tables(0).keys()
                    ), "block table already exists(layer0)"

        # NOTE: Here we assume that all sequences in the group have the same
        # prompt.
        seq = waiting_seqs[0]
        block_table_list: List[BlockTable] = self._allocate_sequence_layers(
            seq)
        for layer, block_table in enumerate(block_table_list):
            self.layer_block_tables[layer][seq.seq_id] = block_table

        # Track seq,not supported now
        # self._computed_blocks_tracker.add_seq(seq.seq_id)
        # self._last_access_blocks_tracker.add_seq(seq.seq_id)

        # Assign the block tables for all layers of each sequence
        for seq in waiting_seqs[1:]:
            for layer, block_table in enumerate(block_table_list):
                self.layer_block_tables[layer][seq.seq_id] = block_table.fork()

        # TODO add cross block tables for encoder-decoder model
        # check_no_caching_or_swa_for_blockmgr_encdec(self, seq_group)

    def can_append_slots_layer(self) -> bool:
        pass
        return True

    def can_append_slots(self, seq_group: SequenceGroup,
                         num_lookahead_slots: int) -> bool:
        # 常规方法，判断是否可以为一个seq_group的所有层分配slots，块数要乘以层数
        # 不可以在step_layer中调用，因为step_layer中只考虑一个层

        num_touched_blocks = 0
        for seq in seq_group.get_seqs(status=SequenceStatus.RUNNING):
            block_table = self.block_tables(0)[seq.seq_id]
            num_touched_blocks += (
                block_table.get_num_blocks_touched_by_append_slots(
                    token_ids=block_table.get_unseen_token_ids(
                        seq.get_token_ids()),
                    num_lookahead_slots=num_lookahead_slots,
                ))

        num_free_gpu_blocks = (
            self.num_attn_layers *
            self.block_allocator.get_num_free_blocks(Device.GPU))
        return num_touched_blocks <= num_free_gpu_blocks

    def can_append_slots_all(self, seq_groups: List[SequenceGroup],
                             num_lookahead_slots: int) -> bool:
        # 检查是否可以为running队列中的所有seq_group分配slots，是否所有层？
        pass
        return True

    # def append_slots(
    #     self,
    #     seq: Sequence,
    #     num_lookahead_slots: int,
    # ) -> List[Tuple[int, int]]:
    #     pass

    # def fork(self, parent_seq: Sequence, child_seq: Sequence) -> None:
    #     pass

    # def can_swap_in(
    #     self, seq_group: SequenceGroup, num_lookahead_slots: int
    # ) -> AllocStatus:
    #     pass

    # def swap_in(self, seq_group: SequenceGroup) -> List[Tuple[int, int]]:
    #     pass

    # def can_swap_out(self, seq_group: SequenceGroup) -> bool:
    #     pass

    # def swap_out(self, seq_group: SequenceGroup) -> List[Tuple[int, int]]:
    #     pass

    # def free(self, seq: Sequence) -> None:
    #     pass

    # def get_block_table(self, seq: Sequence) -> List[int]:
    #     pass

    # def get_num_free_gpu_blocks(self) -> int:
    #     pass

    # def get_num_free_cpu_blocks(self) -> int:
    #     pass

    # def access_all_blocks_in_seq(
    #     self,
    #     seq: Sequence,
    #     access_time: float,
    # ) -> None:
    #     pass

    # def get_common_computed_block_ids(
    #     self, seqs: List[Sequence]
    # ) -> GenericSequence[int]:
    #     pass

    # def mark_blocks_as_computed(
    #     self, seq_group: SequenceGroup, token_chunk_size: int
    # ):
    #     pass

    # def get_prefix_cache_hit_rate(self, device: Device) -> float:
    #     """Prefix cache hit rate. -1 means not supported or disabled."""
    #     pass
